---
     # setting php5 and php5-fpm

  #   # /etc/php5/fpm/php.ini
  # - name: open php5 cgi.fix_pathinfo=1
  #   command: grep -E ";cgi.fix_pathinfo=1" /etc/php5/fpm/php.ini
  #   ignore_errors: True
  #   register: no_find_cgi_path

  #   # if can't fin ";cgi.fix_pathinfo=1" in php.ini.
  #   # maybe had open this function
  # - name: check cgi.fix_pathinfo=1 if opened
  #   command: grep -E "cgi.fix_pathinfo=1" /etc/php5/fpm/php.ini
  #   ignore_errors: True
  #   register: check_cgi_path
  #   when: no_find_cgi_path.rc!=0 

  # - name: Can't find "cgi.fix_pathinfo=1" in /etc/php5/fpm/php.ini
  #   fail: msg=" Can't find cgi.fix_pathinfo=1 in /etc/php5/fpm/php.ini"
  #   when: no_find_cgi_path.rc!=0 and check_cgi_path.rc!=0

  # # if find ";cgi.fix_pathinfo=1" open this function
  # - name: find ;cgi.fix_pathinfo=1
  #   command: sed -i s/";cgi.fix_pathinfo=1"/"cgi.fix_pathinfo=1"/g /etc/php5/fpm/php.ini
  #   when: no_find_cgi_path.rc==0


    - lineinfile: dest=/etc/php5/fpm/php.ini 
                  regexp="^;cgi.fix_pathinfo=1" 
                  line="cgi.fix_pathinfo=1"
                  state=present

 
   #----------------------------------------------------------------#
   # add "listen = 127.0.0.1:9000" to /etc/php5/fpm/pool.d/www.conf
   # In our nginx setting (/etc/nginx/sites-availabel/owncloud)
   # we set "upstream php-handler{ } " to listen 127.0.0.1:9000

   #- name: add listen 127.0.0.1:9000
   # # command: sed -i '$a listen 127.0.0.1:9000' /etc/php5/fpm/pool.d/www.conf 
   #  command: bash -c "echo \"listen = 127.0.0.1:9000\" | tee -a /etc/php5/fpm/pool.d/www.conf"
    - lineinfile: dest=/etc/php5/fpm/pool.d/www.conf
                 state=present
                 insertafter="EOF"
                 line="listen = 127.0.0.1:9000"
      notify:
          - restart php5-fpm 
     
